title: Wali's Blog
email: keepcrow@outlook.com
description: > 
  学一点是一点
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: 王广宇 # add your name
author-pic: puff-face.jpg
about-author: 猫咪就是救世主

# Contact links
email: keepcrow@outlook.com 
phone: 17889982151
website: keepcrow.github.io # Add your website, do not add http://
github: keepcrow

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
